"""
OnyxAlways Orders — Backend
============================
Single-file FastAPI service for managing custom print/design orders.

Why single-file? For a solo business, fewer files = less cognitive load.
Everything (models, schemas, routes, app) lives here. If this grows past
~500 lines, split into modules: models.py / schemas.py / routes/.

Run locally:  uvicorn main:app --reload --host 0.0.0.0 --port 8000
API docs:     http://localhost:8000/docs   (auto-generated by FastAPI)
App UI:       http://localhost:8000/
"""

from __future__ import annotations

import csv
import io
import os
from collections import defaultdict
from datetime import datetime, date, timedelta
from decimal import Decimal
from enum import Enum
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field, ConfigDict
from sqlalchemy import (
    Column, Integer, String, Text, Numeric, DateTime, Date, Enum as SAEnum,
    create_engine, func, select,
)
from sqlalchemy.orm import declarative_base, sessionmaker, Session

# ---------------------------------------------------------------------------
# Database setup
# ---------------------------------------------------------------------------
# SQLite chosen because:
#   1) Zero-config — a single .db file, easy to back up (just copy the file).
#   2) Plenty fast for a solo business (handles thousands of orders).
#   3) When you outgrow it, swap DATABASE_URL to a Postgres URL — SQLAlchemy
#      handles the rest with no code changes.
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./onyxalways.db")

# `check_same_thread` is a SQLite-only quirk needed for FastAPI's threaded
# request handling. It's a no-op for other databases.
engine_kwargs = {"connect_args": {"check_same_thread": False}} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(DATABASE_URL, **engine_kwargs)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    """FastAPI dependency that yields a DB session and always closes it."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ---------------------------------------------------------------------------
# Domain model
# ---------------------------------------------------------------------------
class OrderStatus(str, Enum):
    """
    Order lifecycle. Enum definition order matters — it defines the
    progression direction used by the /advance and /regress endpoints.
    """
    NEW_ORDER = "NEW_ORDER"                  # Just received, gathering details
    DESIGNING_APPROVAL = "DESIGNING_APPROVAL"  # Working on design / awaiting client sign-off
    PRODUCTION = "PRODUCTION"                # Printing / pressing / manufacturing / ready
    COMPLETE = "COMPLETE"                    # Delivered, paid, done


class Order(Base):
    """
    Core entity. One row per customer order.

    Money fields use Numeric (decimal) — NEVER float for money. Floats
    introduce rounding errors that compound silently and break accounting.
    """
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    client_name = Column(String(120), nullable=False, index=True)
    description = Column(Text, nullable=False)
    item_type = Column(String(60), nullable=False, default="T-Shirt")
    quantity = Column(Integer, nullable=False, default=1)

    # Cost breakdown — split so you can analyze where margin goes
    material_cost = Column(Numeric(10, 2), nullable=False, default=0)
    labor_cost = Column(Numeric(10, 2), nullable=False, default=0)
    sale_price = Column(Numeric(10, 2), nullable=False, default=0)

    status = Column(SAEnum(OrderStatus), nullable=False, default=OrderStatus.NEW_ORDER, index=True)
    notes = Column(Text, nullable=True)

    due_date = Column(Date, nullable=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)


Base.metadata.create_all(bind=engine)


# ---------------------------------------------------------------------------
# Pydantic schemas (request/response contracts)
# ---------------------------------------------------------------------------
# Separating SQLAlchemy models from Pydantic schemas is intentional:
# the DB shape and the API shape are allowed to differ, and you don't
# want internal columns leaking out as API fields.

class OrderBase(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    client_name: str = Field(..., min_length=1, max_length=120)
    description: str = Field(..., min_length=1)
    item_type: str = Field(default="T-Shirt", max_length=60)
    quantity: int = Field(default=1, ge=1)
    material_cost: Decimal = Field(default=Decimal("0"), ge=0)
    labor_cost: Decimal = Field(default=Decimal("0"), ge=0)
    sale_price: Decimal = Field(default=Decimal("0"), ge=0)
    notes: Optional[str] = None
    due_date: Optional[date] = None


class OrderCreate(OrderBase):
    """Schema for POST /orders — status defaults to INTAKE server-side."""
    pass


class OrderUpdate(BaseModel):
    """All fields optional — PATCH semantics."""
    model_config = ConfigDict(from_attributes=True)

    client_name: Optional[str] = Field(None, min_length=1, max_length=120)
    description: Optional[str] = None
    item_type: Optional[str] = None
    quantity: Optional[int] = Field(None, ge=1)
    material_cost: Optional[Decimal] = Field(None, ge=0)
    labor_cost: Optional[Decimal] = Field(None, ge=0)
    sale_price: Optional[Decimal] = Field(None, ge=0)
    status: Optional[OrderStatus] = None
    notes: Optional[str] = None
    due_date: Optional[date] = None


class OrderOut(OrderBase):
    id: int
    status: OrderStatus
    created_at: datetime
    updated_at: datetime
    completed_at: Optional[datetime] = None

    # Computed fields — calculated, not stored. Single source of truth.
    @property
    def total_cost(self) -> Decimal:
        return (self.material_cost or Decimal("0")) + (self.labor_cost or Decimal("0"))

    @property
    def profit(self) -> Decimal:
        return (self.sale_price or Decimal("0")) - self.total_cost


class OrderResponse(BaseModel):
    """Full response shape including computed fields."""
    model_config = ConfigDict(from_attributes=True)

    id: int
    client_name: str
    description: str
    item_type: str
    quantity: int
    material_cost: Decimal
    labor_cost: Decimal
    sale_price: Decimal
    total_cost: Decimal
    profit: Decimal
    status: OrderStatus
    notes: Optional[str]
    due_date: Optional[date]
    created_at: datetime
    updated_at: datetime
    completed_at: Optional[datetime]


class SummaryResponse(BaseModel):
    """Dashboard accounting summary."""
    active_orders: int
    completed_orders: int
    outstanding_revenue: Decimal  # Sum of sale_price for non-completed orders
    month_revenue: Decimal         # Completed this calendar month
    month_profit: Decimal
    lifetime_profit: Decimal


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _to_response(o: Order) -> OrderResponse:
    """Convert ORM Order to API response, computing derived fields."""
    total_cost = (o.material_cost or Decimal("0")) + (o.labor_cost or Decimal("0"))
    profit = (o.sale_price or Decimal("0")) - total_cost
    return OrderResponse(
        id=o.id,
        client_name=o.client_name,
        description=o.description,
        item_type=o.item_type,
        quantity=o.quantity,
        material_cost=o.material_cost,
        labor_cost=o.labor_cost,
        sale_price=o.sale_price,
        total_cost=total_cost,
        profit=profit,
        status=o.status,
        notes=o.notes,
        due_date=o.due_date,
        created_at=o.created_at,
        updated_at=o.updated_at,
        completed_at=o.completed_at,
    )


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------
app = FastAPI(
    title="OnyxAlways Orders API",
    description="Order management for OnyxAlways custom print & design work.",
    version="1.0.0",
)

# CORS open by default since the frontend is served from the same origin.
# Tighten this if you ever serve the frontend from a different domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ----- API routes ----------------------------------------------------------
@app.get("/api/health")
def health():
    """Cheap liveness check — useful for uptime monitors and deploy probes."""
    return {"status": "ok", "service": "onyxalways-orders"}


@app.get("/api/orders", response_model=list[OrderResponse])
def list_orders(
    status_filter: Optional[OrderStatus] = None,
    db: Session = Depends(get_db),
):
    """List all orders, optionally filtered by status. Newest first."""
    query = db.query(Order)
    if status_filter:
        query = query.filter(Order.status == status_filter)
    orders = query.order_by(Order.created_at.desc()).all()
    return [_to_response(o) for o in orders]


@app.get("/api/orders/{order_id}", response_model=OrderResponse)
def get_order(order_id: int, db: Session = Depends(get_db)):
    order = db.query(Order).filter(Order.id == order_id).first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    return _to_response(order)


@app.post("/api/orders", response_model=OrderResponse, status_code=status.HTTP_201_CREATED)
def create_order(payload: OrderCreate, db: Session = Depends(get_db)):
    """Create a new order. Always starts in NEW_ORDER status."""
    order = Order(**payload.model_dump(), status=OrderStatus.NEW_ORDER)
    db.add(order)
    db.commit()
    db.refresh(order)
    return _to_response(order)


@app.patch("/api/orders/{order_id}", response_model=OrderResponse)
def update_order(order_id: int, payload: OrderUpdate, db: Session = Depends(get_db)):
    """Partial update — only fields present in the payload are touched."""
    order = db.query(Order).filter(Order.id == order_id).first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")

    data = payload.model_dump(exclude_unset=True)

    # If status is being changed to COMPLETE, stamp completed_at.
    # If it's being moved BACK from complete, clear completed_at.
    if "status" in data:
        new_status = data["status"]
        if new_status == OrderStatus.COMPLETE and order.status != OrderStatus.COMPLETE:
            order.completed_at = datetime.utcnow()
        elif new_status != OrderStatus.COMPLETE and order.status == OrderStatus.COMPLETE:
            order.completed_at = None

    for field, value in data.items():
        setattr(order, field, value)

    db.commit()
    db.refresh(order)
    return _to_response(order)


@app.delete("/api/orders/{order_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_order(order_id: int, db: Session = Depends(get_db)):
    """Hard delete. Use sparingly — better to archive via COMPLETED status."""
    order = db.query(Order).filter(Order.id == order_id).first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")
    db.delete(order)
    db.commit()
    return None


@app.post("/api/orders/{order_id}/advance", response_model=OrderResponse)
def advance_order(order_id: int, db: Session = Depends(get_db)):
    """Move order to next lifecycle stage. Convenience endpoint for kanban."""
    order = db.query(Order).filter(Order.id == order_id).first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")

    progression = list(OrderStatus)
    current_idx = progression.index(order.status)
    if current_idx >= len(progression) - 1:
        raise HTTPException(status_code=400, detail="Order is already complete")

    order.status = progression[current_idx + 1]
    if order.status == OrderStatus.COMPLETE:
        order.completed_at = datetime.utcnow()
    db.commit()
    db.refresh(order)
    return _to_response(order)


@app.post("/api/orders/{order_id}/regress", response_model=OrderResponse)
def regress_order(order_id: int, db: Session = Depends(get_db)):
    """Move order back one stage. For when something needs rework."""
    order = db.query(Order).filter(Order.id == order_id).first()
    if not order:
        raise HTTPException(status_code=404, detail="Order not found")

    progression = list(OrderStatus)
    current_idx = progression.index(order.status)
    if current_idx == 0:
        raise HTTPException(status_code=400, detail="Order is already at first stage")

    order.status = progression[current_idx - 1]
    if order.completed_at:
        order.completed_at = None
    db.commit()
    db.refresh(order)
    return _to_response(order)


@app.get("/api/summary", response_model=SummaryResponse)
def get_summary(db: Session = Depends(get_db)):
    """
    Accounting dashboard data.

    Note: For a tiny dataset this is fine. If you reach tens of thousands of
    orders, replace these scans with a single GROUP BY query or pre-computed
    monthly rollup table.
    """
    all_orders = db.query(Order).all()

    today = date.today()
    month_start = today.replace(day=1)

    active = [o for o in all_orders if o.status != OrderStatus.COMPLETE]
    completed = [o for o in all_orders if o.status == OrderStatus.COMPLETE]

    outstanding_revenue = sum((o.sale_price or Decimal("0") for o in active), Decimal("0"))

    completed_this_month = [
        o for o in completed
        if o.completed_at and o.completed_at.date() >= month_start
    ]
    month_revenue = sum((o.sale_price or Decimal("0") for o in completed_this_month), Decimal("0"))
    month_profit = sum(
        ((o.sale_price or Decimal("0")) - (o.material_cost or Decimal("0")) - (o.labor_cost or Decimal("0"))
         for o in completed_this_month),
        Decimal("0"),
    )
    lifetime_profit = sum(
        ((o.sale_price or Decimal("0")) - (o.material_cost or Decimal("0")) - (o.labor_cost or Decimal("0"))
         for o in completed),
        Decimal("0"),
    )

    return SummaryResponse(
        active_orders=len(active),
        completed_orders=len(completed),
        outstanding_revenue=outstanding_revenue,
        month_revenue=month_revenue,
        month_profit=month_profit,
        lifetime_profit=lifetime_profit,
    )


@app.get("/api/weekly")
def get_weekly(weeks: int = 8, db: Session = Depends(get_db)):
    """
    Per-week order and revenue breakdown for the last N weeks.

    Weeks run Monday–Sunday (ISO standard). Returned newest-first so
    index 0 is always the current week.

    Why Python-side filtering instead of SQL date functions?
    SQLite and Postgres handle date casting differently. Pulling all
    orders and filtering in Python avoids that incompatibility entirely.
    At the scale of a solo business (hundreds, not millions of rows)
    this is perfectly fast.
    """
    today = date.today()
    # Monday of the current ISO week
    current_week_start = today - timedelta(days=today.weekday())

    all_orders = db.query(Order).all()
    result = []

    for i in range(weeks):
        week_start = current_week_start - timedelta(weeks=i)
        week_end = week_start + timedelta(days=6)

        # datetime boundaries for inclusive range matching
        ws_dt = datetime.combine(week_start, datetime.min.time())
        we_dt = datetime.combine(week_end, datetime.max.time())

        created_this_week = [
            o for o in all_orders
            if ws_dt <= o.created_at <= we_dt
        ]
        completed_this_week = [
            o for o in all_orders
            if o.status == OrderStatus.COMPLETE
            and o.completed_at
            and ws_dt <= o.completed_at <= we_dt
        ]

        revenue = sum(
            (o.sale_price or Decimal("0") for o in completed_this_week),
            Decimal("0"),
        )
        profit = sum(
            (
                (o.sale_price or Decimal("0"))
                - (o.material_cost or Decimal("0"))
                - (o.labor_cost or Decimal("0"))
                for o in completed_this_week
            ),
            Decimal("0"),
        )

        # Item type tally for orders created this week
        item_breakdown: dict[str, int] = {}
        for o in created_this_week:
            item_breakdown[o.item_type] = item_breakdown.get(o.item_type, 0) + 1

        result.append({
            "week_start":        week_start.isoformat(),
            "week_end":          week_end.isoformat(),
            "is_current":        i == 0,
            "new_orders":        len(created_this_week),
            "completed_orders":  len(completed_this_week),
            "revenue":           str(revenue),
            "profit":            str(profit),
            "item_breakdown":    item_breakdown,
        })

    return result


@app.get("/api/analytics")
def get_analytics(db: Session = Depends(get_db)):
    """
    Full business intelligence breakdown for OnyxAlways.

    Financial metrics (revenue, profit, margin) use COMPLETED orders only —
    because an open order hasn't generated real revenue yet.
    Job creation counts include all statuses to show pipeline activity.

    Three sections:
      by_item_type  — which items to market more (sorted by total profit)
      monthly       — month-by-month pipeline and revenue view
      kpi           — headline numbers + three marketing intelligence signals
    """
    all_orders = db.query(Order).all()
    completed  = [o for o in all_orders if o.status == OrderStatus.COMPLETE]

    def _profit(o: Order) -> Decimal:
        return (
            (o.sale_price     or Decimal("0"))
            - (o.material_cost or Decimal("0"))
            - (o.labor_cost    or Decimal("0"))
        )

    # ── By Item Type ──────────────────────────────────────────────────────────
    item_map: dict[str, dict] = defaultdict(lambda: {
        "job_count":         0,
        "total_revenue":     Decimal("0"),
        "total_material":    Decimal("0"),
        "total_profit":      Decimal("0"),
    })
    for o in completed:
        d = item_map[o.item_type]
        d["job_count"]      += 1
        d["total_revenue"]  += o.sale_price     or Decimal("0")
        d["total_material"] += o.material_cost  or Decimal("0")
        d["total_profit"]   += _profit(o)

    total_completed = len(completed)

    by_item_type = []
    for item_type, d in sorted(item_map.items(), key=lambda x: x[1]["total_profit"], reverse=True):
        count   = d["job_count"]
        revenue = d["total_revenue"]
        profit  = d["total_profit"]

        freq_pct  = round(count / total_completed * 100, 1) if total_completed else 0.0
        margin    = (profit / revenue * 100).quantize(Decimal("0.1")) if revenue else Decimal("0")
        avg_profit = (profit / count).quantize(Decimal("0.01"))       if count   else Decimal("0")

        by_item_type.append({
            "item_type":        item_type,
            "job_count":        count,
            "frequency_pct":    freq_pct,
            "total_revenue":    str(revenue),
            "total_material":   str(d["total_material"]),
            "total_profit":     str(profit),
            "avg_profit_per_job": str(avg_profit),
            "margin_pct":       str(margin),
        })

    # ── Monthly Breakdown ─────────────────────────────────────────────────────
    month_created:   dict[tuple, int]  = defaultdict(int)
    month_completed_data: dict[tuple, dict] = defaultdict(lambda: {
        "jobs_completed": 0,
        "revenue":        Decimal("0"),
        "material":       Decimal("0"),
        "profit":         Decimal("0"),
    })

    for o in all_orders:
        month_created[(o.created_at.year, o.created_at.month)] += 1

    for o in completed:
        if o.completed_at:
            key = (o.completed_at.year, o.completed_at.month)
            dc = month_completed_data[key]
            dc["jobs_completed"] += 1
            dc["revenue"]   += o.sale_price    or Decimal("0")
            dc["material"]  += o.material_cost or Decimal("0")
            dc["profit"]    += _profit(o)

    month_names = ["Jan","Feb","Mar","Apr","May","Jun",
                   "Jul","Aug","Sep","Oct","Nov","Dec"]
    all_keys = set(month_created) | set(month_completed_data)

    monthly = []
    for (year, month) in sorted(all_keys, reverse=True):
        dc      = month_completed_data[(year, month)]
        revenue = dc["revenue"]
        profit  = dc["profit"]
        margin  = (profit / revenue * 100).quantize(Decimal("0.1")) if revenue else Decimal("0")

        monthly.append({
            "month_label":    f"{month_names[month - 1]} {year}",
            "year":           year,
            "month":          month,
            "jobs_created":   month_created[(year, month)],
            "jobs_completed": dc["jobs_completed"],
            "revenue":        str(revenue),
            "material":       str(dc["material"]),
            "profit":         str(profit),
            "margin_pct":     str(margin),
        })

    # ── KPI Summary ───────────────────────────────────────────────────────────
    if completed:
        total_revenue = sum((o.sale_price or Decimal("0") for o in completed), Decimal("0"))
        total_profit  = sum((_profit(o)                   for o in completed), Decimal("0"))
        overall_margin = (
            (total_profit / total_revenue * 100).quantize(Decimal("0.1"))
            if total_revenue else Decimal("0")
        )
        avg_revenue = (total_revenue / len(completed)).quantize(Decimal("0.01"))
        avg_profit  = (total_profit  / len(completed)).quantize(Decimal("0.01"))

        # Marketing signals — only meaningful when there are multiple item types
        best_margin   = max(by_item_type, key=lambda x: float(x["margin_pct"]))    if by_item_type else None
        most_frequent = max(by_item_type, key=lambda x: x["job_count"])             if by_item_type else None
        top_profit    = by_item_type[0]                                              if by_item_type else None
    else:
        total_revenue = total_profit = overall_margin = avg_revenue = avg_profit = Decimal("0")
        best_margin = most_frequent = top_profit = None

    kpi = {
        "total_all_orders":        len(all_orders),
        "total_completed_orders":  total_completed,
        "total_revenue":           str(total_revenue),
        "total_profit":            str(total_profit),
        "avg_revenue_per_order":   str(avg_revenue),
        "avg_profit_per_order":    str(avg_profit),
        "overall_margin_pct":      str(overall_margin),
        "best_margin_item":        best_margin["item_type"]  if best_margin   else None,
        "best_margin_pct":         best_margin["margin_pct"] if best_margin   else None,
        "most_frequent_item":      most_frequent["item_type"]   if most_frequent else None,
        "most_frequent_count":     most_frequent["job_count"]   if most_frequent else None,
        "top_profit_contributor":  top_profit["item_type"]   if top_profit    else None,
        "top_profit_total":        top_profit["total_profit"] if top_profit    else None,
    }

    return {"by_item_type": by_item_type, "monthly": monthly, "kpi": kpi}


@app.get("/api/export")
def export_csv(db: Session = Depends(get_db)):
    """
    Download all completed orders as a CSV file.

    Ready to open in Excel for ad-hoc analysis (pivot tables, custom charts).
    All financial figures are pre-calculated so no Excel formulas are needed.
    Use this instead of maintaining a parallel spreadsheet — the app is the
    source of truth; Excel is for one-off deep dives from clean exported data.
    """
    completed = (
        db.query(Order)
        .filter(Order.status == OrderStatus.COMPLETE)
        .order_by(Order.completed_at.desc())
        .all()
    )

    buf = io.StringIO()
    writer = csv.writer(buf)

    writer.writerow([
        "Order ID", "Client Name", "Description", "Item Type", "Quantity",
        "Material Cost ($)", "Sale Price ($)", "Profit ($)", "Margin %",
        "Created Date", "Completed Date",
    ])

    for o in completed:
        revenue = o.sale_price    or Decimal("0")
        profit  = revenue - (o.material_cost or Decimal("0")) - (o.labor_cost or Decimal("0"))
        margin  = (profit / revenue * 100).quantize(Decimal("0.1")) if revenue else Decimal("0")

        writer.writerow([
            f"OA-{str(o.id).zfill(4)}",
            o.client_name,
            o.description,
            o.item_type,
            o.quantity,
            f"{o.material_cost or 0:.2f}",
            f"{revenue:.2f}",
            f"{profit:.2f}",
            f"{margin}%",
            o.created_at.strftime("%Y-%m-%d"),
            o.completed_at.strftime("%Y-%m-%d") if o.completed_at else "",
        ])

    buf.seek(0)
    filename = f"onyxalways-{datetime.now().strftime('%Y%m%d')}.csv"

    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
# Serving the frontend from the same FastAPI process keeps deployment to
# ONE container / ONE process. No separate web server, no CORS issues.
STATIC_DIR = Path(__file__).parent / "static"

if STATIC_DIR.exists():
    @app.get("/")
    def root():
        return FileResponse(STATIC_DIR / "index.html")

    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
